package com.base.portfolio.presentation.module.dashboard.screens.technicalskills.model

import com.base.portfolio.R

val technicalSkillsList = listOf(
    "Java",
    "Kotlin",
    "SQLite",
    "RoomDB",
    "Material Design",
    "XML",
    "Jetpack",
    "UI/UX",
    "Git",
    "Bitbucket",
    "RxJava",
    "Firebase",
    "Kotlin Coroutines",
    "Agile",
    "Scrum",
    "Kotlin Flows",
    "Jira",
    "Android Studio",
    "Eclipse",
    "Stripe",
    "Razorpay",
    "Visual Studio",
    "Android SDK",
    "ADB",
    "Google Play Console",
    "Application Deployment",
    "BLE Integration",
    "Dependency Injection",
    "Dagger",
    "Hilt",
    "App signing",
    "Crash reports",
    "Bug tracking",
    "Retrofit",
    "Volley",
    "JSON",
    "Debugging",
    "Profiling",
    "Performance Optimization",
    "Time Management",
    "Communication",
    "Problem Solving",
    "Adaptability",
    "Leadership",
    "Creativity",
    "Innovative",
    "Team Collaboration"
)

val technicalSkillsImages = listOf(
    R.drawable.room,
    R.drawable.roomdb,
    R.drawable.android,
    R.drawable.coroutines,
    R.drawable.jirasoftware,
    R.drawable.firebase,
    R.drawable.git,
    R.drawable.jetpackcompose,
    R.drawable.java,
    R.drawable.retrofit,
    R.drawable.jira
)